"""Migração inicial

Revision ID: 1ebeefd59c7a
Revises: 963d51aac47b
Create Date: 2025-10-22 17:57:03.037307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebeefd59c7a'
down_revision = '963d51aac47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prioridade_minima_emergencia', sa.Integer(), nullable=True))

    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_individual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saldo_minimo_para_desligar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desligar_automatico', sa.Boolean(), nullable=True))
        batch_op.drop_column('limite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('desligar_automatico')
        batch_op.drop_column('saldo_minimo_para_desligar')
        batch_op.drop_column('limite_individual')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('prioridade_minima_emergencia')

    # ### end Alembic commands ###
