"""Migração inicial

Revision ID: 6191121c347f
Revises: 
Create Date: 2025-10-19 07:42:17.128263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6191121c347f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limite_pzem1', sa.Float(), nullable=True),
    sa.Column('limite_pzem2', sa.Float(), nullable=True),
    sa.Column('preco_kwh', sa.Float(), nullable=True),
    sa.Column('email_notificacao', sa.String(length=120), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_telegram', sa.Boolean(), nullable=True),
    sa.Column('saldo_kwh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pzem_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_peaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_peaks_date'), ['date'], unique=False)

    op.create_table('energy_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pzem_id', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('pf', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('pzem_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_peaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_peaks_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_peaks_year'), ['year'], unique=False)

    op.create_table('recargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_mzn', sa.Float(), nullable=False),
    sa.Column('taxa_lixo', sa.Float(), nullable=True),
    sa.Column('taxa_radio', sa.Float(), nullable=True),
    sa.Column('iva_percent', sa.Float(), nullable=True),
    sa.Column('kwh_creditados', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recargas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recargas_criado_em'), ['criado_em'], unique=False)

    op.create_table('reles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('pzem_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('limite', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('pzem_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_peaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_peaks_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_peaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_peaks_week_start'))

    op.drop_table('weekly_peaks')
    op.drop_table('users')
    op.drop_table('reles')
    with op.batch_alter_table('recargas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recargas_criado_em'))

    op.drop_table('recargas')
    with op.batch_alter_table('monthly_peaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_peaks_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_peaks_month'))

    op.drop_table('monthly_peaks')
    op.drop_table('energy_data')
    with op.batch_alter_table('daily_peaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_peaks_date'))

    op.drop_table('daily_peaks')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
