"""Migração inicial

Revision ID: 963d51aac47b
Revises: 6191121c347f
Create Date: 2025-10-19 15:45:05.083241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963d51aac47b'
down_revision = '6191121c347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_lixo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taxa_radio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iva_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('recargas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_kwh', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('saldo_anterior', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('saldo_atual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recargas', schema=None) as batch_op:
        batch_op.drop_column('saldo_atual')
        batch_op.drop_column('saldo_anterior')
        batch_op.drop_column('preco_kwh')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('iva_percent')
        batch_op.drop_column('taxa_radio')
        batch_op.drop_column('taxa_lixo')

    # ### end Alembic commands ###
